spring:
  application:
    name: ikeda-authuser-ms
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ikeda-config-server
      username: configserver
      password: '123456GHJKLMN'