server:
  port: 8087
  servlet:
    context-path: '/ikeda-authuser/'

spring:
  application:
    name: ikeda-authuser-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/ikeda-authuser
    username: postgres
    password: zaq1@wsx
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always

ikeda:
  api:
    url:
      register: 'http://ikeda-register-ms/ikeda-register'

logging:
  level:
    com.ikeda: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
