server:
  port: 8087
  servlet:
    context-path: '/ikeda-authuser/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ikeda-authuser
    username: postgres
    password: zaq1@wsx
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true